### ISSUE TITLE
Bug & Suggestions from Discord

### ISSUE THREAD

**Issue by originalaidn** [counterstrikesharp-panel/css-bans#89]
- The oldest appears first on the mute list, not the newest (ID 1 not 500)
- Adding admin name to Recent Bans & Mutes (i think it need a config to enable/disable it)
- Add posibility to use permanent when adding/editing VIP user
- Adding logs into unmute, edit mute etc
- On dashboard add a select server list to top players
- Add mute type (GAG, MUTE, SILENCE) into mute list (on dashboard too)
- Remove "Profile" from dashboard, adding a href into players name

**Comment by ghostt187** [comment]
another suggestion

can u add option when banning thru website for example a player which has a name like this "Ghost Test" when banning thru website it bans css_ban ghost test 1440 which is a problem since the player has seperated name and it registeres as permanent ban can u add " " to the nickname so the ban happens like this css_ban "ghost test" 1440
